function init(obj)
%UISCROLLPANEL/INIT   Scalar-object one-time initialization during construction
%   INIT(OBJ) is called by the HGSETGETEX's constructor and shall
%   initialize OBJ's internal properties that are must be initialized prior
%   to setting any of its public properties or calling any of its public
%   methods. Before implementing necessary actions for the class, it should
%   call the INIT() of the superclass first.

% run superclass init first
obj.init@uipanelautoresize();

obj.propopts.Canvas = struct([]);
obj.propopts.Window = struct([]);
obj.propopts.CanvasOrigin = struct(...
   'OtherTypeDesc',{{'[x0 y0]'}},...
   'OtherTypeValidator',{{{'numeric'},{'numel',2,'finite'}}});
obj.propopts.CanvasSize = struct(...
   'OtherTypeDesc',{{'[width height]'}},...
   'OtherTypeValidator',{{{'numeric'},{'numel',2,'positive','finite'}}});
obj.propopts.CanvasUnits = struct(...
   'StringOptions',{{'inches','centimeters','normalized','points','pixels','characters'}});
obj.propopts.ResizeFcnMode = struct(...
   'StringOptions',{{'manual' 'auto'}});
obj.propopts.HorizontalAlignment = struct(...
   'StringOptions',{{'left' 'center' 'right'}},...
   'Default','center');
obj.propopts.HorizontalScrollbar = struct(...
   'StringOptions',{{'off' 'on'}},...
   'Default','on');
obj.propopts.HorizontalScrollbarLocation = struct(...
   'StringOptions',{{'bottom' 'top'}},...
   'Default','bottom');
obj.propopts.HorizontalScrollbarAutoHide = struct(...
   'StringOptions',{{'off' 'on'}},...
   'Default','on');
obj.propopts.HorizontalScrollbarStep = struct(...
   'OtherTypeDesc',{{'[positive scalar]'}},...
   'OtherTypeValidator',{{{'numeric'},{'scalar','positive','finite'}}},...
   'Default',10);
obj.propopts.ScrollbarThickness = struct(...
   'OtherTypeDesc',{{'[positive scalar in pixels]'}},...
   'OtherTypeValidator',{{{'numeric'},{'scalar','positive'}}},...
   'Default',15);
obj.propopts.VerticalAlignment = struct(...
   'StringOptions',{{'bottom' 'middle' 'top'}},...
   'Default','middle');
obj.propopts.VerticalScrollbar = struct(...
   'StringOptions',{{'off' 'on'}},...
   'Default','on');
obj.propopts.VerticalScrollbarLocation = struct(...
   'StringOptions',{{'left' 'right'}},...
   'Default','right');
obj.propopts.VerticalScrollbarAutoHide = struct(...
   'StringOptions',{{'off' 'on'}},...
   'Default','on');
obj.propopts.VerticalScrollbarStep = struct(...
   'OtherTypeDesc',{{'[positive scalar]'}},...
   'OtherTypeValidator',{{{'numeric'},{'scalar','positive','finite'}}},...
   'Default',10);

obj.propopts.WindowSize = struct([]);

obj.sortpropopts([],false,false,true,true);
