function init(obj)
%UIZOOMCTRL/PROPOPTS   Returns set/get property attribute cell

obj.init@uipanelautoresize();
obj.init@zoompanctrl();

obj.btns = struct('pointer',[],'zoomin',[],'zoomout',[],'pan',[]);
obj.jbtns = struct('pointer',[],'zoomin',[],'zoomout',[],'pan',[]);
obj.btnstates = struct('pointer',true,'zoomin',true,'zoomout',true,'pan',true);
obj.panelsize = [0 0];
obj.el_btnstates = handle([]);

obj.propopts.AutoLayout.Default = 'on';
obj.propopts.SupportedModes.StringOptions = [{'pointer'},obj.propopts.SupportedModes.StringOptions];
obj.propopts.SupportedModes.Default = obj.propopts.SupportedModes.StringOptions;

obj.propopts.DefaultMode = struct(...
   'StringOptions',{{'pointer','zoomin','zoomout','pan'}},...
   'Default','pointer');
obj.propopts.AllowUnselect = struct(...
   'StringOptions',{{'on' 'off'}},...
   'Default','on');
obj.propopts.PointerEnable = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.ZoomInEnable = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.ZoomOutEnable = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.PanEnable = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});

obj.propopts.PointerVisible = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.ZoomInVisible = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.ZoomOutVisible = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});
obj.propopts.PanVisible = struct(...
   'EmptyAllowed',true,...
   'StringOptions',{{'on','off'}});

obj.propopts.ButtonSize = struct(...
   'OtherTypeValidator',{{{'numeric'},{'scalar','positive','finite'}}},...
   'Default',18);

obj.propopts.PointerTooltipString = struct(...
   'OtherTypeValidator',{{{'char'},{'row'}}});
obj.propopts.UIReady = struct(...
   'StringOptions',{{'on','off'}});

obj.sortpropopts([],false,false,true,true);
