function init(obj)
%UIFILECONTROL/INIT   Scalar-object one-time initialization during construction
%   INIT(OBJ) is called by the HGSETGETEX's constructor and shall
%   initialize OBJ's internal properties that are must be initialized prior
%   to setting any of its public properties or calling any of its public
%   methods. Before implementing necessary actions for the class, it should
%   call the INIT() of the superclass first.
%

obj.init@hgauxctrl();

% place the aux control to the right of the main control
obj.aux_loc = 2;% {1-'left',2-'right',3-'bottom',4-'top}
obj.aux_valign = 3;  % {1-'bottom',2-'middle',3-'top',0-'fill'}

% initialize internal variables that are not indirectly initialized by
% public property defaults
obj.dialogtitle = {};
obj.filtspec = {};
obj.histlist = cell(0,2);
obj.histmax = 5;
obj.format = true;

obj.propopts.FileName = struct(...
   'OtherTypeValidator',@(val)obj.validatefile(val,2));
obj.propopts.FolderPath = struct(...
   'OtherTypeValidator',@(val)obj.validatefile(val,3),...
   'Default',pwd);
obj.propopts.FilePath = struct(...
   'OtherTypeValidator',@(val)obj.validatefile(val,1));

obj.propopts.FileIODirection = struct(...
   'StringOptions', {{'put','get'}},...
   'Default','get');
obj.propopts.FileFilterSpec = struct(...
   'OtherTypeValidator',@(val)ischar(val)||(iscellstr(val)&&size(val,2)<=2),...
   'Default',{{'*.*', 'All Files (*.*)'}});
obj.propopts.FileHistory = struct(...
   'StringOptions',{{'off','on'}},...
   'Default','off');
obj.propopts.FileHistoryList = struct(...
   'OtherTypeValidator',@iscellstr);
obj.propopts.FileHistoryDepth = struct(...
   'OtherTypeValidator',{{{'numeric'},{'scalar','nonnegative','integer'}}},...
   'Default',5);
obj.propopts.FileDialogTitle = struct(...
   'OtherTypeValidator',{{{'char'},{'row'}}});
obj.propopts.FileDisplayOption = struct(...
   'StringOptions',{{'fullpath','nameonly'}},...
   'Default','nameonly');

obj.sortpropopts([],false,false,true,true);
