function init(obj)
%HGANDLABELS/INIT   Scalar-object one-time initialization during construction
%   INIT(OBJ) is called by the HGSETGETEX's constructor and shall
%   initialize OBJ's internal properties that are must be initialized prior
%   to setting any of its public properties or calling any of its public
%   methods. Before implementing necessary actions for the class, it should
%   call the INIT() of the superclass first.

obj.init@hgauxctrl();

obj.icons = {[],[]};
obj.ttstrs = {'',''};

obj.propopts.LockedIcon = struct(...
   'MixedType',true,...
   'StringOptions',{{'auto'}},...
   'OtherTypeDesc',{{'RGB image matrix'}},...
   'OtherTypeValidator',@isrgb,...
   'Default','auto');
obj.propopts.UnlockedIcon = struct(...
   'MixedType',true,...
   'StringOptions',{{'auto'}},...
   'OtherTypeDesc',{{'RGB image matrix'}},...
   'OtherTypeValidator',@isrgb,...
   'Default','auto');
obj.propopts.LockedTooltipString = struct(...
   'OtherTypeValidator',@(val)ischar(val)&&(isempty(val)||isrow(val)),...
   'Default','Click to unlock');
obj.propopts.UnlockedTooltipString = struct(...
   'OtherTypeValidator',@(val)ischar(val)&&(isempty(val)||isrow(val)),...
   'Default','Click to lock');

obj.propopts.LockHandle = struct([]);
obj.propopts.Locked = struct(...
   'StringOptions',{{'off','on'}});
obj.propopts.LockedAction = struct(...
   'StringOptions',{{'none','disable','inactive'}},...
   'Default','inactive');
obj.propopts.LockLocation = struct(...
   'StringOptions',{{'west','east','south','north'}},...
   'Default','east');
obj.propopts.LockHorizontalAlignment = struct(...
   'StringOptions',{{'left','center','right'}},...
   'Default','right');
obj.propopts.LockVerticalAlignment = struct(...
   'StringOptions',{{'bottom','middle','top'}},...
   'Default','middle');
obj.propopts.LockVisible = struct(...
   'StringOptions',{{'off','on'}});
obj.propopts.LockEnable = struct(...
   'StringOptions',{{'on','off','inactive'}});

obj.sortpropopts([],false,false,true,true);

end

function tf = isrgb(val)

tf = isa(val,'double')&&ndims(val)==3&&size(val,3)==3&&all(val(:)>=0)&&all(val(:)<=1);

end
